In [ ]:
from datasets import load_dataset

In [ ]:
files = {
}
files['train'] = '/data/gj/data/imdb/train.json'
files['test'] = '/data/gj/data/imdb/test.json'

raws = load_dataset('json', data_files=files, cache_dir='/data/gj/Bi-Attention-HFTrainer/data')

In [ ]:
raws

In [ ]:
from datasets import load_
xxx = load_from_disk('/data/gj/data/imdb/train.json')

In [ ]:
from transformers import LlamaConfig

config = LlamaConfig.from_pretrained('/data/gj/llama-7b-hf')

In [ ]:
config.is_decoder

In [ ]:
from transformers import BartConfig
cfg = BartConfig.from_pretrained('/data/gj/bart-large')

In [ ]:
cfg.is_encoder_decoder

In [ ]:
cfg

In [ ]:

from fastchat.model.model_adapter import get_conversation_template

conv = get_conversation_template('vicuna')

In [ ]:
from transformers import LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained('/data/gj/vicuna-7b-v1.3')

In [ ]:
tokenizer(conv.get_prompt())

In [ ]:
from rouge_score import rouge_scorer

s = rouge_scorer.RougeScorer(["rouge1", "rouge2"])
x = s.score('gao jun', 'gao ju')



In [ ]:
round(x['rouge1']*100, 4)

In [ ]:
import evaluate
import os

os.environ['http_proxy'] = '10.40.6.125:7890'
os.environ['https_proxy'] = '10.40.6.125:7890'

In [ ]:
metric = evaluate.load('rouge')

In [ ]:
from peft import AutoPeftModelForCausalLM

In [ ]:
model = AutoPeftModelForCausalLM.from_pretrained('/data/gj/Bi-Attention-HFTrainer/output_dir/test')

In [ ]:
import os
import evaluate

os.environ['http_proxy'] = '10.40.51.67:7890'
os.environ['https_proxy'] = '10.40.51.67:7890'

acc = evaluate.load('seqeval')

In [ ]:
y_true = [['O', 'O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'O', 'B-PER', 'I-PER']]
y_pred = [['O', 'O', 'B-MISC', 'I-MISC', 'B-MISC', 'I-MISC', 'O', 'B-PER', 'I-PER']]

acc.compute(predictions=y_pred, references=y_true)

In [ ]:
x = {'a': 1, 'b': 2}

In [ ]:
y = {v: k for k, v in x.items()}

In [ ]:
import torch.nn as nn

loss = nn.CrossEntropyLoss()

In [ ]:
import torch
x = nn.functional.softmax(torch.randn((9, 9)), dim=-1)

In [ ]:
[i for i in x for j in i]

In [ ]:
labels = torch.arange(9)

In [ ]:
labels

In [ ]:
loss(x, labels)

In [ ]:
labels.shape

In [ ]:
import numpy as np

def map_numbers_to_letters(matrix, mapping):
    map_func = np.vectorize(lambda num: mapping.get(num, ' '))
    letter_matrix = map_func(matrix)
    return letter_matrix

# 示例字典和矩阵
letter_mapping = {1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}
matrix = np.array([[1, 2, 3], [4, 5, 6]])



In [ ]:
map_numbers_to_letters(matrix, letter_mapping)



In [ ]:
a = [1, 2, None, None]

In [ ]:
a.remove(None)

In [ ]:
a

In [ ]:
x

In [ ]:
x.masked_fill(x<0.2, -100)

In [ ]:
a = torch.randn((3,4,5))

In [ ]:
m = torch.randn((3, 4)) > 0

In [ ]:
m

In [ ]:
a.masked_fill(m.unsqueeze(dim=-1), -100)

In [ ]:
import numpy as np

preds = np.random.random((4, 5))
lables = np.random.random((4, 5))

In [ ]:
preds = np.where(lables<0.5, preds, np.full_like(lables, -100))

In [ ]:
preds

In [ ]:
lables

In [74]:
conll_ner_tags_mapping = {'O': 0, 'B-PER': 1, 'I-PER': 2, 'B-ORG': 3, 'I-ORG': 4, 'B-LOC': 5, 'I-LOC': 6, 'B-MISC': 7, 'I-MISC': 8}
conll_ner_tags_mapping = {v: k for k, v in conll_ner_tags_mapping.items()}


def postprocess_ner_ids(preds, labels):
    map_func = np.vectorize(lambda num: conll_ner_tags_mapping.get(num, ''))
    preds = np.where(labels != -100, preds, np.full_like(preds, -100))
    preds = map_func(preds).tolist()
    labels = map_func(labels).tolist()
    
    for pred in preds:
        pred[:] = [p for p in pred if p != '']
            
    for label in labels:
        label[:] = [l for l in label if l != '']
    
    return preds, labels 

In [75]:
preds = np.array([[1,2,3], [4,5,6]])
labels = np.array([[-100, 2, -100], [-100, 5, 4]])

In [76]:
preds, labels = postprocess_ner_ids(preds, labels)

In [77]:
import evaluate
import os
os.environ['http_proxy'] = '10.40.51.67:7890'
os.environ['https_proxy'] = '10.40.51.67:7890'
metric = evaluate.load('seqeval')


In [ ]:
preds.tolist().pop('')

In [79]:
metric.compute(predictions=preds, references=labels)

/data/gj/miniconda3/envs/biattention/lib/python3.9/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'LOC': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1},
 'ORG': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 1},
 'PER': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 1},
 'overall_precision': 0.5,
 'overall_recall': 0.3333333333333333,
 'overall_f1': 0.4,
 'overall_accuracy': 0.6666666666666666}

In [86]:
multiply(result, 10)

{'a': {'x': 50.0, 'y': 40.0}, 'b': 60.0}

In [2]:
from peft import AutoPeftModelForCausalLM

model = AutoPeftModelForCausalLM.from_pretrained('/data/gj/Bi-Attention-HFTrainer/output_dir/test/checkpoint-8')

/data/gj/miniconda3/envs/biattention/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[2023-10-21 19:31:50,717] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


Loading checkpoint shards: 100%|██████████| 2/2 [00:12<00:00,  6.44s/it]
Some weights of the model checkpoint at /data/gj/models/vicuna-7b-v1.3 were not used when initializing LlamaModel: ['lm_head.weight']
- This IS expected if you are initializing LlamaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [1]:
import safetensors.torch

In [40]:
state_dict = safetensors.torch.load_file('/data/gj/Bi-Attention-HFTrainer/output_dir/test/checkpoint-4/adapter_model.safetensors', device="cpu")

In [19]:
b = safetensors.torch.load_file('/data/gj/Bi-Attention-HFTrainer/output_dir/test/checkpoint-8/adapter_model.safetensors', device="cpu")

In [26]:
b['base_model.model.layers.0.self_attn.k_proj.lora_A.weight']

tensor([[ 1.1198e-02, -1.8330e-03,  1.5624e-02,  ...,  1.4411e-02,
          6.1283e-03,  1.5579e-02],
        [-7.6152e-03,  6.2727e-03, -1.3887e-02,  ...,  9.2982e-03,
         -1.1437e-05, -5.0887e-04],
        [-1.4586e-02, -7.0003e-03,  1.2569e-02,  ...,  7.8880e-03,
         -7.2497e-03, -7.3856e-03],
        ...,
        [-9.9548e-03, -3.0787e-04,  7.9469e-03,  ...,  3.0999e-03,
         -1.4552e-02, -8.0941e-03],
        [ 8.8106e-03, -9.5266e-03, -8.2273e-03,  ..., -1.1473e-02,
          8.0957e-03, -1.3063e-02],
        [ 7.1870e-03, -2.7483e-03, -9.8101e-03,  ..., -3.1905e-03,
          1.1243e-02, -1.3782e-02]])

In [25]:
for n, p in model.named_parameters():
    if 'lora' in n:
        print(p)
        break

Parameter containing:
tensor([[ 1.1198e-02, -1.8330e-03,  1.5624e-02,  ...,  1.4411e-02,
          6.1283e-03,  1.5579e-02],
        [-7.6152e-03,  6.2727e-03, -1.3887e-02,  ...,  9.2982e-03,
         -1.1437e-05, -5.0887e-04],
        [-1.4586e-02, -7.0003e-03,  1.2569e-02,  ...,  7.8880e-03,
         -7.2497e-03, -7.3856e-03],
        ...,
        [-9.9548e-03, -3.0787e-04,  7.9469e-03,  ...,  3.0999e-03,
         -1.4552e-02, -8.0941e-03],
        [ 8.8106e-03, -9.5266e-03, -8.2273e-03,  ..., -1.1473e-02,
          8.0957e-03, -1.3063e-02],
        [ 7.1870e-03, -2.7483e-03, -9.8101e-03,  ..., -3.1905e-03,
          1.1243e-02, -1.3782e-02]])


In [27]:
n

'base_model.model.layers.0.self_attn.k_proj.lora_A.default.weight'

In [41]:
state_dict = {k[:-6]+'default.weight': v for k, v in state_dict.items()}

In [42]:
state_dict.keys()

dict_keys(['base_model.model.layers.0.self_attn.k_proj.lora_A.default.weight', 'base_model.model.layers.0.self_attn.k_proj.lora_B.default.weight', 'base_model.model.layers.0.self_attn.v_proj.lora_A.default.weight', 'base_model.model.layers.0.self_attn.v_proj.lora_B.default.weight', 'base_model.model.layers.1.self_attn.k_proj.lora_A.default.weight', 'base_model.model.layers.1.self_attn.k_proj.lora_B.default.weight', 'base_model.model.layers.1.self_attn.v_proj.lora_A.default.weight', 'base_model.model.layers.1.self_attn.v_proj.lora_B.default.weight', 'base_model.model.layers.10.self_attn.k_proj.lora_A.default.weight', 'base_model.model.layers.10.self_attn.k_proj.lora_B.default.weight', 'base_model.model.layers.10.self_attn.v_proj.lora_A.default.weight', 'base_model.model.layers.10.self_attn.v_proj.lora_B.default.weight', 'base_model.model.layers.11.self_attn.k_proj.lora_A.default.weight', 'base_model.model.layers.11.self_attn.k_proj.lora_B.default.weight', 'base_model.model.layers.11.sel

In [43]:
model.load_state_dict(state_dict, False)

_IncompatibleKeys(missing_keys=['base_model.model.embed_tokens.weight', 'base_model.model.layers.0.self_attn.q_proj.weight', 'base_model.model.layers.0.self_attn.k_proj.weight', 'base_model.model.layers.0.self_attn.v_proj.weight', 'base_model.model.layers.0.self_attn.o_proj.weight', 'base_model.model.layers.0.self_attn.rotary_emb.inv_freq', 'base_model.model.layers.0.mlp.gate_proj.weight', 'base_model.model.layers.0.mlp.down_proj.weight', 'base_model.model.layers.0.mlp.up_proj.weight', 'base_model.model.layers.0.input_layernorm.weight', 'base_model.model.layers.0.post_attention_layernorm.weight', 'base_model.model.layers.1.self_attn.q_proj.weight', 'base_model.model.layers.1.self_attn.k_proj.weight', 'base_model.model.layers.1.self_attn.v_proj.weight', 'base_model.model.layers.1.self_attn.o_proj.weight', 'base_model.model.layers.1.self_attn.rotary_emb.inv_freq', 'base_model.model.layers.1.mlp.gate_proj.weight', 'base_model.model.layers.1.mlp.down_proj.weight', 'base_model.model.layers.

In [45]:
for n, p in model.named_parameters():
    if 'lora' in n:
        print(p)
        break

Parameter containing:
tensor([[ 1.1194e-02, -1.8372e-03,  1.5615e-02,  ...,  1.4414e-02,
          6.1241e-03,  1.5570e-02],
        [-7.6161e-03,  6.2772e-03, -1.3879e-02,  ...,  9.2896e-03,
         -1.0831e-06, -4.9550e-04],
        [-1.4587e-02, -6.9995e-03,  1.2557e-02,  ...,  7.8875e-03,
         -7.2573e-03, -7.3969e-03],
        ...,
        [-9.9545e-03, -3.0631e-04,  7.9381e-03,  ...,  3.1013e-03,
         -1.4561e-02, -8.1029e-03],
        [ 8.7975e-03, -9.5347e-03, -8.2265e-03,  ..., -1.1474e-02,
          8.0903e-03, -1.3070e-02],
        [ 7.1723e-03, -2.7537e-03, -9.7997e-03,  ..., -3.1994e-03,
          1.1245e-02, -1.3780e-02]])


In [47]:
state_dict['base_model.model.layers.0.self_attn.k_proj.lora_A.default.weight']

tensor([[ 1.1194e-02, -1.8372e-03,  1.5615e-02,  ...,  1.4414e-02,
          6.1241e-03,  1.5570e-02],
        [-7.6161e-03,  6.2772e-03, -1.3879e-02,  ...,  9.2896e-03,
         -1.0831e-06, -4.9550e-04],
        [-1.4587e-02, -6.9995e-03,  1.2557e-02,  ...,  7.8875e-03,
         -7.2573e-03, -7.3969e-03],
        ...,
        [-9.9545e-03, -3.0631e-04,  7.9381e-03,  ...,  3.1013e-03,
         -1.4561e-02, -8.1029e-03],
        [ 8.7975e-03, -9.5347e-03, -8.2265e-03,  ..., -1.1474e-02,
          8.0903e-03, -1.3070e-02],
        [ 7.1723e-03, -2.7537e-03, -9.7997e-03,  ..., -3.1994e-03,
          1.1245e-02, -1.3780e-02]])

In [48]:
b['base_model.model.layers.0.self_attn.k_proj.lora_A.weight']

tensor([[ 1.1198e-02, -1.8330e-03,  1.5624e-02,  ...,  1.4411e-02,
          6.1283e-03,  1.5579e-02],
        [-7.6152e-03,  6.2727e-03, -1.3887e-02,  ...,  9.2982e-03,
         -1.1437e-05, -5.0887e-04],
        [-1.4586e-02, -7.0003e-03,  1.2569e-02,  ...,  7.8880e-03,
         -7.2497e-03, -7.3856e-03],
        ...,
        [-9.9548e-03, -3.0787e-04,  7.9469e-03,  ...,  3.0999e-03,
         -1.4552e-02, -8.0941e-03],
        [ 8.8106e-03, -9.5266e-03, -8.2273e-03,  ..., -1.1473e-02,
          8.0957e-03, -1.3063e-02],
        [ 7.1870e-03, -2.7483e-03, -9.8101e-03,  ..., -3.1905e-03,
          1.1243e-02, -1.3782e-02]])

In [4]:
from peft import PeftModel

In [5]:
isinstance(model, PeftModel)

True

In [8]:
import os
os.path.isfile('/data/gj/Bi-Attention-HFTrainer/output_dir/test/checkpoint-8')

False

In [9]:
a = {'a': 1}
b = {'b': 2}

In [11]:
a.update(b)

In [12]:
a

{'a': 1, 'b': 2}

In [13]:
def flatten_dict(d, parent_key='', sep='_'):
    items = {}
    for key, value in d.items():
        new_key = f"{parent_key}{sep}{key}" if parent_key else key
        if isinstance(value, dict):
            items.update(flatten_dict(value, new_key, sep=sep))
        else:
            items[new_key] = value
    return items

# 示例嵌套字典
nested_dict = {
    'a': 1,
    'b': {
        'c': 2,
        'd': {
            'e': 3
        }
    },
    'f': 4
}

# 调用函数摊平字典
flat_dict = flatten_dict(nested_dict)
print(flat_dict)

{'a': 1, 'b_c': 2, 'b_d_e': 3, 'f': 4}


In [2]:
import evaluate
import os 

os.environ['http_proxy'] = '10.40.50.225:7890'
os.environ['https_proxy'] = '10.40.50.225:7890'
acc = evaluate.load('accuracy')
precision = evaluate.load('precision')

In [3]:
recall = evaluate.load('recall')

In [4]:
a = [0,0,1]
b = [0,1,1]


In [8]:
z = acc.compute(predictions=a, references=b)

In [9]:
y = precision.compute(predictions=a, references=b)

In [10]:
x = recall.compute(predictions=a, references=b)

In [14]:
x.update(y)
x.update(z)

In [15]:
x

{'recall': 0.5, 'precision': 1.0, 'accuracy': 0.6666666666666666}

In [16]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'b': 3, 'c': 4}

merged_dict = {key: value for d in [dict1, dict2] for key, value in d.items()}
print(merged_dict)

{'a': 1, 'b': 3, 'c': 4}


In [3]:
import safetensors.torch

model = safetensors.torch.load_file('/data/gj/Bi-Attention-HFTrainer/output_dir/naive-vicuna-bi-nlu/checkpoint-7200/model.safetensors', device='cpu')

In [4]:
model

{'bias': tensor([-0.0012, -0.0057]),
 'weight': tensor([[ 0.0143,  0.0015, -0.0131,  ..., -0.0001, -0.0145,  0.0036],
         [-0.0092, -0.0137,  0.0185,  ...,  0.0116,  0.0198,  0.0063]])}

In [6]:
from transformers import AutoModel

model = AutoModel.from_pretrained('/data/gj/Bi-Attention-HFTrainer/output_dir/naive-vicuna-bi-nlu/checkpoint-7200')

OSError: /data/gj/Bi-Attention-HFTrainer/output_dir/naive-vicuna-bi-nlu/checkpoint-7200 does not appear to have a file named config.json. Checkout 'https://huggingface.co//data/gj/Bi-Attention-HFTrainer/output_dir/naive-vicuna-bi-nlu/checkpoint-7200/None' for available files.